/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  "aws_project_region": "us-west-2",
  "aws_cognito_identity_pool_id": "us-west-2:18dea874-b418-4330-9306-470729e6748c",
  "aws_cognito_region": "us-west-2",
  "aws_user_pools_id": "us-west-2_rHOLZeBIK",
  "aws_user_pools_web_client_id": "3r722v0507j2s2vq66jk935b12",
  "aws_appsync_graphqlEndpoint": "https://cmz7h56izvfifpxfyoeuat3tbe.appsync-api.us-west-2.amazonaws.com/graphql",
  "oauth": {},
  "aws_cognito_username_attributes": [],
  "aws_cognito_social_providers": [],
  "aws_cognito_signup_attributes": [
      "EMAIL"
  ],
  "aws_cognito_mfa_configuration": "OFF",
  "aws_cognito_mfa_types": [
      "SMS"
  ],
  "aws_cognito_password_protection_settings": {
      "passwordPolicyMinLength": 8,
      "passwordPolicyCharacters": []
  },
  "aws_cognito_verification_mechanisms": [
      "EMAIL"
  ],
  "aws_rds": {
    "mydb": {
      "host": "database-1.cbkknefcjewr.us-west-2.rds.amazonaws.com",
      "port": "3306",
      "username": "admin",
      "password": "burger",
      "database": "mydb",
      "awsSecretStoreArn": "arn:aws:secretsmanager:us-west-2:791852914748:secret:corgi-ZxTupU"
    }
  }
};


export default awsmobile;
  